# Dependencies
markdown:         kramdown
highlighter:      rouge


# Setup
title:            Cybercarnet de notes
tagline:          'par Frédéric Letellier'
description:      'Bien écrire, c''est déjà presque bien penser, et il n''y a pas loin de là jusqu''à bien agir. -Thomas Mann'
url:              http://fredericletellier.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Frédéric Letellier'
  url:

paginate:         20
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0.0
#sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/compte14031879
